version: '3.8'

services:
  memcached:
    image: memcached:1.6-alpine
    platform: linux/arm64
    ports:
      - "11212:11211"  # Expose memcached on port 11212
    command: ["-v"]  # Verbose mode to see requests
    container_name: bifrost-memcached

  # Optional: Add another memcached for testing multiple backends later
  memcached2:
    image: memcached:1.6-alpine
    platform: linux/arm64
    ports:
      - "11213:11211"
    command: ["-v"]
    container_name: bifrost-memcached2